import { Model, DataTypes, Sequelize, type Optional } from "sequelize";
interface UserAttributes {
    id: number;
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    address: string;
    phoneNumber: string;
    gender: boolean;
    image?: string | null;
    roleId: string;
    positionId: string;
    createdAt?: Date;
    updatedAt?: Date;
}
type UserCreationAttributes = Optional<UserAttributes, "id" | "image" | "createdAt" | "updatedAt">;
declare const _default: (sequelize: Sequelize) => {
    new (values?: Optional<UserCreationAttributes, import("sequelize/lib/utils").NullishPropertiesOf<UserCreationAttributes>> | undefined, options?: import("sequelize").BuildOptions): {
        id: number;
        email: string;
        password: string;
        firstName: string;
        lastName: string;
        address: string;
        phoneNumber: string;
        gender: boolean;
        image: string | null;
        roleId: string;
        positionId: string;
        readonly createdAt: Date;
        readonly updatedAt: Date;
        _attributes: UserAttributes;
        dataValues: UserAttributes;
        _creationAttributes: UserCreationAttributes;
        isNewRecord: boolean;
        sequelize: Sequelize;
        where(): object;
        getDataValue<K extends keyof UserAttributes>(key: K): UserAttributes[K];
        setDataValue<K extends keyof UserAttributes>(key: K, value: UserAttributes[K]): void;
        get(options?: {
            plain?: boolean;
            clone?: boolean;
        }): UserAttributes;
        get<K extends keyof /*elided*/ any>(key: K, options?: {
            plain?: boolean;
            clone?: boolean;
        }): /*elided*/ any[K];
        get(key: string, options?: {
            plain?: boolean;
            clone?: boolean;
        }): unknown;
        set<K extends keyof UserAttributes>(key: K, value: UserAttributes[K], options?: import("sequelize").SetOptions): /*elided*/ any;
        set(keys: Partial<UserAttributes>, options?: import("sequelize").SetOptions): /*elided*/ any;
        setAttributes<K extends keyof UserAttributes>(key: K, value: UserAttributes[K], options?: import("sequelize").SetOptions): /*elided*/ any;
        setAttributes(keys: Partial<UserAttributes>, options?: import("sequelize").SetOptions): /*elided*/ any;
        changed<K extends keyof /*elided*/ any>(key: K): boolean;
        changed<K extends keyof /*elided*/ any>(key: K, dirty: boolean): void;
        changed(): false | string[];
        previous(): Partial<UserAttributes>;
        previous<K extends keyof UserAttributes>(key: K): UserAttributes[K] | undefined;
        save(options?: import("sequelize").SaveOptions<UserAttributes> | undefined): Promise</*elided*/ any>;
        reload(options?: import("sequelize").FindOptions<UserAttributes> | undefined): Promise</*elided*/ any>;
        validate(options?: import("sequelize/lib/instance-validator").ValidationOptions): Promise<void>;
        update<K extends keyof UserAttributes>(key: K, value: import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal | UserAttributes[K], options?: import("sequelize").InstanceUpdateOptions<UserAttributes> | undefined): Promise</*elided*/ any>;
        update(keys: {
            id?: number | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            email?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            password?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            firstName?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            lastName?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            address?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            phoneNumber?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            gender?: boolean | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            image?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal | null;
            roleId?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            positionId?: string | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            createdAt?: Date | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
            updatedAt?: Date | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal;
        }, options?: import("sequelize").InstanceUpdateOptions<UserAttributes> | undefined): Promise</*elided*/ any>;
        destroy(options?: import("sequelize").InstanceDestroyOptions): Promise<void>;
        restore(options?: import("sequelize").InstanceRestoreOptions): Promise<void>;
        increment<K extends keyof UserAttributes>(fields: Partial<UserAttributes> | K | readonly K[], options?: import("sequelize").IncrementDecrementOptionsWithBy<UserAttributes> | undefined): Promise</*elided*/ any>;
        decrement<K extends keyof UserAttributes>(fields: Partial<UserAttributes> | K | readonly K[], options?: import("sequelize").IncrementDecrementOptionsWithBy<UserAttributes> | undefined): Promise</*elided*/ any>;
        equals(other: /*elided*/ any): boolean;
        equalsOneOf(others: readonly /*elided*/ any[]): boolean;
        toJSON<T extends UserAttributes>(): T;
        toJSON(): object;
        isSoftDeleted(): boolean;
        _model: Model<UserAttributes, UserCreationAttributes>;
        addHook<K extends keyof import("sequelize/lib/hooks").SequelizeHooks<M, TModelAttributes, TCreationAttributes>>(hookType: K, name: string, fn: import("sequelize/lib/hooks").SequelizeHooks<Model<any, any>, UserAttributes, UserCreationAttributes>[K]): /*elided*/ any;
        addHook<K extends keyof import("sequelize/lib/hooks").SequelizeHooks<M, TModelAttributes, TCreationAttributes>>(hookType: K, fn: import("sequelize/lib/hooks").SequelizeHooks<Model<UserAttributes, UserCreationAttributes>, UserAttributes, UserCreationAttributes>[K]): /*elided*/ any;
        removeHook<K extends keyof import("sequelize/lib/hooks").SequelizeHooks<M, TModelAttributes, TCreationAttributes>>(hookType: K, name: string): /*elided*/ any;
        hasHook<K extends keyof import("sequelize/lib/hooks").SequelizeHooks<M, TModelAttributes, TCreationAttributes>>(hookType: K): boolean;
        hasHooks<K extends keyof import("sequelize/lib/hooks").SequelizeHooks<M, TModelAttributes, TCreationAttributes>>(hookType: K): boolean;
    };
    associate(models: any): void;
    readonly tableName: string;
    readonly primaryKeyAttribute: string;
    readonly primaryKeyAttributes: readonly string[];
    readonly associations: {
        [key: string]: import("sequelize").Association;
    };
    readonly options: import("sequelize").InitOptions;
    readonly rawAttributes: {
        [attribute: string]: import("sequelize").ModelAttributeColumnOptions;
    };
    getAttributes<M extends Model>(this: import("sequelize").ModelStatic<M>): { readonly [Key in keyof import("sequelize").Attributes<M>]: import("sequelize").ModelAttributeColumnOptions; };
    readonly sequelize?: Sequelize;
    init<MS extends import("sequelize").ModelStatic<Model>, M extends InstanceType<MS>>(this: MS, attributes: import("sequelize").ModelAttributes<M, Optional<import("sequelize").Attributes<M>, (import("sequelize").Attributes<M> extends infer T ? { [P in keyof T]-?: (keyof NonNullable<T[P]> extends Exclude<keyof NonNullable<T[P]>, Brand> ? false : true) extends true ? P : never; } : never)[keyof import("sequelize").Attributes<M>]>>, options: import("sequelize").InitOptions<M>): MS;
    removeAttribute(attribute: string): void;
    sync<M extends Model>(options?: import("sequelize").SyncOptions): Promise<M>;
    drop(options?: import("sequelize").DropOptions): Promise<void>;
    schema<M extends Model>(this: import("sequelize").ModelStatic<M>, schema: string, options?: import("sequelize").SchemaOptions): import("sequelize").ModelCtor<M>;
    getTableName(): string | {
        tableName: string;
        schema: string;
        delimiter: string;
    };
    scope<M extends Model>(this: import("sequelize").ModelStatic<M>, options?: string | import("sequelize").ScopeOptions | readonly (string | import("sequelize").ScopeOptions)[] | import("sequelize").WhereAttributeHash<M>): import("sequelize").ModelCtor<M>;
    addScope<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, scope: import("sequelize").FindOptions<import("sequelize").Attributes<M>>, options?: import("sequelize").AddScopeOptions): void;
    addScope<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, scope: (...args: readonly any[]) => import("sequelize").FindOptions<import("sequelize").Attributes<M>>, options?: import("sequelize").AddScopeOptions): void;
    findAll<M extends Model>(this: import("sequelize").ModelStatic<M>, options?: import("sequelize").FindOptions<import("sequelize").Attributes<M>>): Promise<M[]>;
    findByPk<M extends Model>(this: import("sequelize").ModelStatic<M>, identifier: import("sequelize").Identifier, options: Omit<import("sequelize").NonNullFindOptions<import("sequelize").Attributes<M>>, "where">): Promise<M>;
    findByPk<M extends Model>(this: import("sequelize").ModelStatic<M>, identifier?: import("sequelize").Identifier, options?: Omit<import("sequelize").FindOptions<import("sequelize").Attributes<M>>, "where">): Promise<M | null>;
    findOne<M extends Model>(this: import("sequelize").ModelStatic<M>, options: import("sequelize").NonNullFindOptions<import("sequelize").Attributes<M>>): Promise<M>;
    findOne<M extends Model>(this: import("sequelize").ModelStatic<M>, options?: import("sequelize").FindOptions<import("sequelize").Attributes<M>>): Promise<M | null>;
    aggregate<T, M extends Model>(this: import("sequelize").ModelStatic<M>, field: keyof import("sequelize").Attributes<M> | "*", aggregateFunction: string, options?: import("sequelize").AggregateOptions<T, import("sequelize").Attributes<M>>): Promise<T>;
    count<M extends Model>(this: import("sequelize").ModelStatic<M>, options: import("sequelize").CountWithOptions<import("sequelize").Attributes<M>>): Promise<import("sequelize").GroupedCountResultItem[]>;
    count<M extends Model>(this: import("sequelize").ModelStatic<M>, options?: Omit<import("sequelize").CountOptions<import("sequelize").Attributes<M>>, "group">): Promise<number>;
    findAndCountAll<M extends Model>(this: import("sequelize").ModelStatic<M>, options?: Omit<import("sequelize").FindAndCountOptions<import("sequelize").Attributes<M>>, "group">): Promise<{
        rows: M[];
        count: number;
    }>;
    findAndCountAll<M extends Model>(this: import("sequelize").ModelStatic<M>, options: import("sequelize/lib/utils/set-required").SetRequired<import("sequelize").FindAndCountOptions<import("sequelize").Attributes<M>>, "group">): Promise<{
        rows: M[];
        count: import("sequelize").GroupedCountResultItem[];
    }>;
    max<T extends DataTypes.DataType | unknown, M extends Model>(this: import("sequelize").ModelStatic<M>, field: keyof import("sequelize").Attributes<M>, options?: import("sequelize").AggregateOptions<T, import("sequelize").Attributes<M>>): Promise<T>;
    min<T extends DataTypes.DataType | unknown, M extends Model>(this: import("sequelize").ModelStatic<M>, field: keyof import("sequelize").Attributes<M>, options?: import("sequelize").AggregateOptions<T, import("sequelize").Attributes<M>>): Promise<T>;
    sum<T extends DataTypes.DataType | unknown, M extends Model>(this: import("sequelize").ModelStatic<M>, field: keyof import("sequelize").Attributes<M>, options?: import("sequelize").AggregateOptions<T, import("sequelize").Attributes<M>>): Promise<number>;
    build<M extends Model>(this: import("sequelize").ModelStatic<M>, record?: import("sequelize").CreationAttributes<M>, options?: import("sequelize").BuildOptions): M;
    bulkBuild<M extends Model>(this: import("sequelize").ModelStatic<M>, records: ReadonlyArray<import("sequelize").CreationAttributes<M>>, options?: import("sequelize").BuildOptions): M[];
    create<M extends Model, O extends import("sequelize").CreateOptions<import("sequelize").Attributes<M>> = import("sequelize").CreateOptions<import("sequelize").Attributes<M>>>(this: import("sequelize").ModelStatic<M>, values?: import("sequelize").CreationAttributes<M>, options?: O): Promise<O extends {
        returning: false;
    } | {
        ignoreDuplicates: true;
    } ? void : M>;
    findOrBuild<M extends Model>(this: import("sequelize").ModelStatic<M>, options: import("sequelize").FindOrBuildOptions<import("sequelize").Attributes<M>, import("sequelize").CreationAttributes<M>>): Promise<[M, boolean]>;
    findOrCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, options: import("sequelize").FindOrCreateOptions<import("sequelize").Attributes<M>, import("sequelize").CreationAttributes<M>>): Promise<[M, boolean]>;
    findCreateFind<M extends Model>(this: import("sequelize").ModelStatic<M>, options: import("sequelize").FindOrCreateOptions<import("sequelize").Attributes<M>, import("sequelize").CreationAttributes<M>>): Promise<[M, boolean]>;
    upsert<M extends Model>(this: import("sequelize").ModelStatic<M>, values: import("sequelize").CreationAttributes<M>, options?: import("sequelize").UpsertOptions<import("sequelize").Attributes<M>>): Promise<[M, boolean | null]>;
    bulkCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, records: ReadonlyArray<import("sequelize").CreationAttributes<M>>, options?: import("sequelize").BulkCreateOptions<import("sequelize").Attributes<M>>): Promise<M[]>;
    truncate<M extends Model>(this: import("sequelize").ModelStatic<M>, options?: import("sequelize").TruncateOptions<import("sequelize").Attributes<M>>): Promise<void>;
    destroy<M extends Model>(this: import("sequelize").ModelStatic<M>, options?: import("sequelize").DestroyOptions<import("sequelize").Attributes<M>>): Promise<number>;
    restore<M extends Model>(this: import("sequelize").ModelStatic<M>, options?: import("sequelize").RestoreOptions<import("sequelize").Attributes<M>>): Promise<void>;
    update<M extends Model>(this: import("sequelize").ModelStatic<M>, values: { [key in keyof import("sequelize").Attributes<M>]?: import("sequelize").Attributes<M>[key] | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal; }, options: Omit<import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>, "returning"> & {
        returning: Exclude<import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>["returning"], undefined | false>;
    }): Promise<[affectedCount: number, affectedRows: M[]]>;
    update<M extends Model>(this: import("sequelize").ModelStatic<M>, values: { [key in keyof import("sequelize").Attributes<M>]?: import("sequelize").Attributes<M>[key] | import("sequelize/lib/utils").Fn | import("sequelize/lib/utils").Col | import("sequelize/lib/utils").Literal; }, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>): Promise<[affectedCount: number]>;
    increment<M extends Model>(this: import("sequelize").ModelStatic<M>, fields: import("sequelize").AllowReadonlyArray<keyof import("sequelize").Attributes<M>>, options: import("sequelize").IncrementDecrementOptionsWithBy<import("sequelize").Attributes<M>>): Promise<[affectedRows: M[], affectedCount?: number]>;
    increment<M extends Model>(this: import("sequelize").ModelStatic<M>, fields: { [key in keyof import("sequelize").Attributes<M>]?: number; }, options: import("sequelize").IncrementDecrementOptions<import("sequelize").Attributes<M>>): Promise<[affectedRows: M[], affectedCount?: number]>;
    decrement<M extends Model>(this: import("sequelize").ModelStatic<M>, fields: import("sequelize").AllowReadonlyArray<keyof import("sequelize").Attributes<M>>, options: import("sequelize").IncrementDecrementOptionsWithBy<import("sequelize").Attributes<M>>): Promise<[affectedRows: M[], affectedCount?: number]>;
    decrement<M extends Model>(this: import("sequelize").ModelStatic<M>, fields: { [key in keyof import("sequelize").Attributes<M>]?: number; }, options: import("sequelize").IncrementDecrementOptions<import("sequelize").Attributes<M>>): Promise<[affectedRows: M[], affectedCount?: number]>;
    describe(): Promise<object>;
    unscoped<M extends import("sequelize").ModelType>(this: M): M;
    beforeValidate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize/lib/instance-validator").ValidationOptions) => import("sequelize/lib/hooks").HookReturn): void;
    beforeValidate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize/lib/instance-validator").ValidationOptions) => import("sequelize/lib/hooks").HookReturn): void;
    afterValidate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize/lib/instance-validator").ValidationOptions) => import("sequelize/lib/hooks").HookReturn): void;
    afterValidate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize/lib/instance-validator").ValidationOptions) => import("sequelize/lib/hooks").HookReturn): void;
    beforeCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize").CreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize").CreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize").CreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize").CreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeDestroy<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize").InstanceDestroyOptions) => import("sequelize/lib/hooks").HookReturn): void;
    beforeDestroy<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize").InstanceDestroyOptions) => import("sequelize/lib/hooks").HookReturn): void;
    afterDestroy<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize").InstanceDestroyOptions) => import("sequelize/lib/hooks").HookReturn): void;
    afterDestroy<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize").InstanceDestroyOptions) => import("sequelize/lib/hooks").HookReturn): void;
    beforeUpdate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeUpdate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterUpdate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterUpdate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeSave<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>> | import("sequelize").SaveOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeSave<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>> | import("sequelize").SaveOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterSave<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instance: M, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>> | import("sequelize").SaveOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterSave<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instance: M, options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>> | import("sequelize").SaveOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeBulkCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instances: M[], options: import("sequelize").BulkCreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeBulkCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instances: M[], options: import("sequelize").BulkCreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterBulkCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instances: readonly M[], options: import("sequelize").BulkCreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterBulkCreate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instances: readonly M[], options: import("sequelize").BulkCreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeBulkDestroy<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (options: import("sequelize").BulkCreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeBulkDestroy<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (options: import("sequelize").BulkCreateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterBulkDestroy<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (options: import("sequelize").DestroyOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterBulkDestroy<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (options: import("sequelize").DestroyOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeBulkUpdate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeBulkUpdate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterBulkUpdate<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterBulkUpdate<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (options: import("sequelize").UpdateOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeFind<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (options: import("sequelize").FindOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeFind<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (options: import("sequelize").FindOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeCount<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (options: import("sequelize").CountOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeCount<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (options: import("sequelize").CountOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeFindAfterExpandIncludeAll<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (options: import("sequelize").FindOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeFindAfterExpandIncludeAll<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (options: import("sequelize").FindOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeFindAfterOptions<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (options: import("sequelize").FindOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeFindAfterOptions<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (options: import("sequelize").FindOptions<import("sequelize").Attributes<M>>) => void): import("sequelize/lib/hooks").HookReturn;
    afterFind<M extends Model>(this: import("sequelize").ModelStatic<M>, name: string, fn: (instancesOrInstance: readonly M[] | M | null, options: import("sequelize").FindOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    afterFind<M extends Model>(this: import("sequelize").ModelStatic<M>, fn: (instancesOrInstance: readonly M[] | M | null, options: import("sequelize").FindOptions<import("sequelize").Attributes<M>>) => import("sequelize/lib/hooks").HookReturn): void;
    beforeBulkSync(name: string, fn: (options: import("sequelize").SyncOptions) => import("sequelize/lib/hooks").HookReturn): void;
    beforeBulkSync(fn: (options: import("sequelize").SyncOptions) => import("sequelize/lib/hooks").HookReturn): void;
    afterBulkSync(name: string, fn: (options: import("sequelize").SyncOptions) => import("sequelize/lib/hooks").HookReturn): void;
    afterBulkSync(fn: (options: import("sequelize").SyncOptions) => import("sequelize/lib/hooks").HookReturn): void;
    beforeSync(name: string, fn: (options: import("sequelize").SyncOptions) => import("sequelize/lib/hooks").HookReturn): void;
    beforeSync(fn: (options: import("sequelize").SyncOptions) => import("sequelize/lib/hooks").HookReturn): void;
    afterSync(name: string, fn: (options: import("sequelize").SyncOptions) => import("sequelize/lib/hooks").HookReturn): void;
    afterSync(fn: (options: import("sequelize").SyncOptions) => import("sequelize/lib/hooks").HookReturn): void;
    hasOne<M extends Model, T extends Model>(this: import("sequelize").ModelStatic<M>, target: import("sequelize").ModelStatic<T>, options?: import("sequelize").HasOneOptions): import("sequelize").HasOne<M, T>;
    belongsTo<M extends Model, T extends Model>(this: import("sequelize").ModelStatic<M>, target: import("sequelize").ModelStatic<T>, options?: import("sequelize").BelongsToOptions): import("sequelize").BelongsTo<M, T>;
    hasMany<M extends Model, T extends Model>(this: import("sequelize").ModelStatic<M>, target: import("sequelize").ModelStatic<T>, options?: import("sequelize").HasManyOptions): import("sequelize").HasMany<M, T>;
    belongsToMany<M extends Model, T extends Model>(this: import("sequelize").ModelStatic<M>, target: import("sequelize").ModelStatic<T>, options: import("sequelize").BelongsToManyOptions): import("sequelize").BelongsToMany<M, T>;
    addHook<H extends import("sequelize/lib/hooks").Hooks, K extends keyof import("sequelize/lib/hooks").SequelizeHooks<H["_model"], import("sequelize").Attributes<H>, import("sequelize").CreationAttributes<H>>>(this: import("sequelize/lib/hooks").HooksStatic<H>, hookType: K, name: string, fn: import("sequelize/lib/hooks").SequelizeHooks<H["_model"], import("sequelize").Attributes<H>, import("sequelize").CreationAttributes<H>>[K]): import("sequelize/lib/hooks").HooksCtor<H>;
    addHook<H extends import("sequelize/lib/hooks").Hooks, K extends keyof import("sequelize/lib/hooks").SequelizeHooks<H["_model"], import("sequelize").Attributes<H>, import("sequelize").CreationAttributes<H>>>(this: import("sequelize/lib/hooks").HooksStatic<H>, hookType: K, fn: import("sequelize/lib/hooks").SequelizeHooks<H["_model"], import("sequelize").Attributes<H>, import("sequelize").CreationAttributes<H>>[K]): import("sequelize/lib/hooks").HooksCtor<H>;
    removeHook<H extends import("sequelize/lib/hooks").Hooks>(this: import("sequelize/lib/hooks").HooksStatic<H>, hookType: keyof import("sequelize/lib/hooks").SequelizeHooks<H["_model"], import("sequelize").Attributes<H>, import("sequelize").CreationAttributes<H>>, name: string): import("sequelize/lib/hooks").HooksCtor<H>;
    hasHook<H extends import("sequelize/lib/hooks").Hooks>(this: import("sequelize/lib/hooks").HooksStatic<H>, hookType: keyof import("sequelize/lib/hooks").SequelizeHooks<H["_model"], import("sequelize").Attributes<H>, import("sequelize").CreationAttributes<H>>): boolean;
    hasHooks<H extends import("sequelize/lib/hooks").Hooks>(this: import("sequelize/lib/hooks").HooksStatic<H>, hookType: keyof import("sequelize/lib/hooks").SequelizeHooks<H["_model"], import("sequelize").Attributes<H>, import("sequelize").CreationAttributes<H>>): boolean;
};
export default _default;
//# sourceMappingURL=user.d.ts.map